--- #Test Playbook
- hosts: localhost
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks: 

  - name: Install basic Dependats
    yum: pkg={{ item }} state=latest
    with_items:
      - bzip2
      - bzip2-libs
      - curl
      - unzip
      - python-pip   
