- hosts: webserver
  vars:
    control_server: mdurvesh1c.mylabserver.com
    web_root: /var/www/html
  tasks:
  - name: Install Lynx on Web Servers
    yum: pkg=lynx state=installed update_cache=true

