--- # WEHN PLAYBOOK EXAMPLE
- hosts: webserver
  user: test
  sudo: yes
  connection: ssh
  vars: 
    playbook_type: conditionalexample
  vars_files: 
#    - /conf/copyright.yml
#    - /conf/webdefaults.yml
  tasks:
   - name: Install Apache appropiate to the Distribution Type (Debain/Ubuntu)
     command: apt-get -y install apache2
     when: ansible_os_family == "Debain"
   - name: Install Apache appropiate to the Distribution Type (Redhat/CentOS)
     command: yum -y install httpd
     when: ansible_os_family == "RedHat"

